#!/usr/bin/env bash
# Generates the per-tool agent rosters from the single source of truth in .ai/agents/.
#
# Claude Code and Copilot use incompatible frontmatter vocabularies, so the roster has to
# exist twice on disk. Only the frontmatter differs — the persona body is shared verbatim.
# Edit .ai/agents/*.md and re-run this. Never hand-edit the generated files.
#
#   bash scripts/gen-agents.sh           regenerate
#   bash scripts/gen-agents.sh --check   verify generated output is current (exit 1 if stale)
#
# Performance note: this does all parsing and emitting in a single awk pass per source file.
# Process creation is expensive under Git Bash on Windows — an earlier version that shelled
# out per frontmatter key and per tool token took minutes. Keep forks out of the loop.
set -euo pipefail

# ---------------------------------------------------------------------------
# Model routing. Replace these placeholders with the real model IDs available
# to you — this is the only place they appear. Agents declare a `tier:`, not a
# model, so re-tiering an agent never means touching a model name.
# Copilot takes a fallback; Claude Code takes the primary only.
# ---------------------------------------------------------------------------
REASONING_MODEL_PRIMARY="${REASONING_MODEL_PRIMARY:-<REASONING_MODEL_PRIMARY>}"
REASONING_MODEL_FALLBACK="${REASONING_MODEL_FALLBACK:-<REASONING_MODEL_FALLBACK>}"
STANDARD_MODEL_PRIMARY="${STANDARD_MODEL_PRIMARY:-<STANDARD_MODEL_PRIMARY>}"
STANDARD_MODEL_FALLBACK="${STANDARD_MODEL_FALLBACK:-<STANDARD_MODEL_FALLBACK>}"
FAST_MODEL_PRIMARY="${FAST_MODEL_PRIMARY:-<FAST_MODEL_PRIMARY>}"
FAST_MODEL_FALLBACK="${FAST_MODEL_FALLBACK:-<FAST_MODEL_FALLBACK>}"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"
src="$root/.ai/agents"

check_mode=0
if [ "${1:-}" = "--check" ]; then
  check_mode=1
elif [ -n "${1:-}" ]; then
  echo "gen-agents: unknown argument '$1' (expected --check or nothing)" >&2
  exit 1
fi

if [ ! -d "$src" ]; then
  echo "gen-agents: no source directory at $src" >&2
  exit 1
fi

if [ "$check_mode" -eq 1 ]; then
  out_root="$(mktemp -d)"
  trap 'rm -rf "$out_root"' EXIT
else
  out_root="$root"
fi
claude_out="$out_root/.claude/agents"
copilot_out="$out_root/.github/agents"
mkdir -p "$claude_out" "$copilot_out"

# Generated output only — wipe so a deleted source doesn't leave an orphan agent behind.
rm -f "$claude_out"/*.md "$copilot_out"/*.agent.md

# One awk pass per source file: parse frontmatter, map capabilities, write both dialects.
emit='
function die(msg) { printf("gen-agents: %s: %s\n", FILENAME, msg) > "/dev/stderr"; exit 1 }

BEGIN {
  claude["read"]    = "Read";        copilot["read"]    = "read"
  claude["search"]  = "Grep, Glob";  copilot["search"]  = "search"
  claude["edit"]    = "Edit, Write"; copilot["edit"]    = "edit"
  claude["execute"] = "Bash";        copilot["execute"] = "execute"
  # Copilot expresses delegation through its `agents:` field, not `tools:`.
  claude["delegate"] = "Agent";      copilot["delegate"] = ""

  split(model_primary,  mp, "\x1f")
  split(model_fallback, mf, "\x1f")
  primary["reasoning"] = mp[1]; fallback["reasoning"] = mf[1]
  primary["standard"]  = mp[2]; fallback["standard"]  = mf[2]
  primary["fast"]      = mp[3]; fallback["fast"]      = mf[3]
}

NR == 1 && $0 != "---" { die("does not start with a --- frontmatter block") }
NR == 1 { inside = 1; next }

inside && $0 == "---" { inside = 0; started = 1; next }

inside {
  i = index($0, ":")
  if (i > 0) {
    k = substr($0, 1, i - 1)
    v = substr($0, i + 1)
    sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v)
    sub(/^"/, "", v); sub(/"$/, "", v)
    meta[k] = v
  }
  next
}

started { body[++n] = $0 }

END {
  if (inside) die("frontmatter block is never closed")
  split("name tier tools description", required, " ")
  for (r = 1; r <= 4; r++)
    if (!(required[r] in meta) || meta[required[r]] == "")
      die("missing frontmatter key \"" required[r] "\"")

  tier = meta["tier"]
  if (tier != "reasoning" && tier != "standard" && tier != "fast")
    die("invalid tier \"" tier "\" (expected reasoning|standard|fast)")

  ntok = split(meta["tools"], toks, ",")
  ctools = ""; ptools = ""
  for (t = 1; t <= ntok; t++) {
    tok = toks[t]
    gsub(/[ \t]/, "", tok)
    if (tok == "") continue
    if (!(tok in claude)) die("unknown capability \"" tok "\"")
    if (claude[tok]  != "") ctools = ctools (ctools  == "" ? "" : ", ") claude[tok]
    if (copilot[tok] != "") ptools = ptools (ptools  == "" ? "" : ", ") copilot[tok]
  }
  if (ctools == "") die("agent declares no tools")

  desc = meta["description"]
  gsub(/"/, "\\\"", desc)

  name   = meta["name"]
  cfile  = claude_dir  "/" name ".md"
  pfile  = copilot_dir "/" name ".agent.md"
  stamp  = "\n<!-- Generated by scripts/gen-agents.sh from .ai/agents/" name ".md — do not edit. -->"

  printf("---\nname: %s\ndescription: \"%s\"\ntools: %s\n# MODEL_TIER: %s\nmodel: %s\n---\n%s\n", \
         name, desc, ctools, tier, primary[tier], stamp) > cfile
  printf("---\ndescription: \"%s\"\ntools: [%s]\nagents: []\n# MODEL_TIER: %s\nmodel: [\"%s\", \"%s\"]\n---\n%s\n", \
         desc, ptools, tier, primary[tier], fallback[tier], stamp) > pfile

  for (i = 1; i <= n; i++) { print body[i] > cfile; print body[i] > pfile }
  close(cfile); close(pfile)
}'

count=0
# Unit separator joins the per-tier model IDs into one -v value; awk splits it back out.
us=$'\x1f'
model_primary="${REASONING_MODEL_PRIMARY}${us}${STANDARD_MODEL_PRIMARY}${us}${FAST_MODEL_PRIMARY}"
model_fallback="${REASONING_MODEL_FALLBACK}${us}${STANDARD_MODEL_FALLBACK}${us}${FAST_MODEL_FALLBACK}"
for file in "$src"/*.md; do
  [ -e "$file" ] || continue
  awk -v claude_dir="$claude_out" -v copilot_dir="$copilot_out" \
      -v model_primary="$model_primary" -v model_fallback="$model_fallback" \
      "$emit" "$file"
  count=$((count + 1))
done

if [ "$count" -eq 0 ]; then
  echo "gen-agents: no agent sources found in $src" >&2
  exit 1
fi

if [ "$check_mode" -eq 1 ]; then
  if diff -r -q "$claude_out" "$root/.claude/agents" >/dev/null 2>&1 &&
     diff -r -q "$copilot_out" "$root/.github/agents" >/dev/null 2>&1; then
    echo "gen-agents: roster is up to date ($count agents)"
    exit 0
  fi
  echo "gen-agents: roster is STALE — run 'bash scripts/gen-agents.sh'" >&2
  diff -r "$root/.claude/agents" "$claude_out" || true
  diff -r "$root/.github/agents" "$copilot_out" || true
  exit 1
fi

echo "gen-agents: wrote $count agents to .claude/agents/ and .github/agents/"
